"""OS 级 Computer Use 能力包。"""  # 新增代码+OSComputerUse: 标记 computer_use 是可导入包；若没有这行代码，旧版 Python 运行方式可能无法稳定导入子模块。
from learning_agent.computer_use.action_policy import POLICY_VERSION, build_action_evidence, prepare_action_arguments, redact_action_arguments  # 新增代码+Phase30ComputerUseActionGate: 对外暴露动作策略、坐标转换和脱敏 helper；如果没有这行代码，验收和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.audit import ComputerUseAuditStore  # 新增代码+Phase31ComputerUseLockAbortEvidence: 对外暴露落盘审计仓库；如果没有这行代码，测试和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.controller import COMPUTER_USE_OBSERVE_OPT_IN_ENV_VAR, ComputerUseActionResult, ComputerUseController, MemoryComputerUseBackend, UnavailableComputerUseBackend, WindowsComputerUseBackend, build_default_computer_use_backend  # 修改代码+Phase28ComputerUse: 对外暴露控制器、测试后端、安全默认后端、Windows 后端、只读观察开关和工厂；如果没有这行代码，调用方需要知道内部文件路径。
from learning_agent.computer_use.evidence import ComputerUseEvidenceStore, FilteredAccessibilityText  # 新增代码+Phase29ComputerUse: 对外暴露证据仓库和 UIA 过滤结果类型；如果没有这行代码，后续阶段无法方便复用 evidence 能力。
from learning_agent.computer_use.helper_client import NullWindowObservationHelper, StaticWindowObservationHelper, WindowObservationPayload  # 新增代码+Phase29ComputerUse: 对外暴露观察 helper 类型；如果没有这行代码，测试和验收脚本需要硬编码内部模块路径。
from learning_agent.computer_use.lock import ComputerUseLockManager  # 新增代码+Phase30ComputerUseActionGate: 对外暴露 durable lock 管理器；如果没有这行代码，验收脚本无法方便获取和释放桌面控制锁。
from learning_agent.computer_use.models import ComputerUseWindowRef  # 新增代码+Phase27ComputerUse: 对外暴露强类型窗口引用；如果没有这行代码，后续 Windows 后端和测试只能从内部路径导入协议模型。
from learning_agent.computer_use.native_diagnostics import WindowsNativeObservationDiagnostics  # 新增代码+Phase33WindowsNativeDiagnostics: 对外暴露 native provider 诊断构建器；如果没有这行代码，验收和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.native_helper import NativeWindowCaptureResult, NativeWindowTextResult, WindowsNativeWindowObservationHelper, parse_hwnd_from_window  # 新增代码+Phase32WindowsNativeHelper: 对外暴露 native helper 和 provider 结果类型；如果没有这行代码，测试和验收脚本需要硬编码内部模块路径。
from learning_agent.computer_use.windows_backend import StaticWindowsWindowInventory, WindowsWindowInventoryProbe, WindowsWindowInventorySnapshot  # 新增代码+Phase28ComputerUse: 对外暴露只读窗口 inventory 类型；如果没有这行代码，后续阶段和学习测试无法方便复用 Phase 28 后端。
__all__ = ["COMPUTER_USE_OBSERVE_OPT_IN_ENV_VAR", "ComputerUseActionResult", "ComputerUseAuditStore", "ComputerUseController", "ComputerUseEvidenceStore", "ComputerUseLockManager", "ComputerUseWindowRef", "FilteredAccessibilityText", "MemoryComputerUseBackend", "NativeWindowCaptureResult", "NativeWindowTextResult", "NullWindowObservationHelper", "POLICY_VERSION", "StaticWindowObservationHelper", "StaticWindowsWindowInventory", "UnavailableComputerUseBackend", "WindowObservationPayload", "WindowsComputerUseBackend", "WindowsNativeObservationDiagnostics", "WindowsNativeWindowObservationHelper", "WindowsWindowInventoryProbe", "WindowsWindowInventorySnapshot", "build_action_evidence", "build_default_computer_use_backend", "parse_hwnd_from_window", "prepare_action_arguments", "redact_action_arguments"]  # 修改代码+Phase33WindowsNativeDiagnostics: 限定公开导出名称并加入 Phase33 diagnostics；如果没有这行代码，from package import * 会遗漏 native provider 诊断能力。
