"""OS 级 Computer Use 能力包。"""  # 新增代码+OSComputerUse: 标记 computer_use 是可导入包；若没有这行代码，旧版 Python 运行方式可能无法稳定导入子模块。
from learning_agent.computer_use.action_policy import POLICY_VERSION, build_action_evidence, prepare_action_arguments, redact_action_arguments  # 新增代码+Phase30ComputerUseActionGate: 对外暴露动作策略、坐标转换和脱敏 helper；如果没有这行代码，验收和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.approval import PHASE38_WINDOWS_COMPUTER_APPROVAL_MARKER, PHASE38_WINDOWS_COMPUTER_APPROVAL_OK_TOKEN, WindowsComputerUseApprovalModel, phase38_cli_line, run_phase38_approval_contract  # 新增代码+Phase38WindowsComputerApproval: 对外暴露 Windows approval 模型和 CLI 合同；如果没有这行代码，验收和终端状态只能硬编码内部模块路径。
from learning_agent.computer_use.audit import ComputerUseAuditStore  # 新增代码+Phase31ComputerUseLockAbortEvidence: 对外暴露落盘审计仓库；如果没有这行代码，测试和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.controller import COMPUTER_USE_OBSERVE_OPT_IN_ENV_VAR, ComputerUseActionResult, ComputerUseController, MemoryComputerUseBackend, UnavailableComputerUseBackend, WindowsComputerUseBackend, build_default_computer_use_backend  # 修改代码+Phase28ComputerUse: 对外暴露控制器、测试后端、安全默认后端、Windows 后端、只读观察开关和工厂；如果没有这行代码，调用方需要知道内部文件路径。
from learning_agent.computer_use.evidence import ComputerUseEvidenceStore, FilteredAccessibilityText  # 新增代码+Phase29ComputerUse: 对外暴露证据仓库和 UIA 过滤结果类型；如果没有这行代码，后续阶段无法方便复用 evidence 能力。
from learning_agent.computer_use.helper_client import NullWindowObservationHelper, StaticWindowObservationHelper, WindowObservationPayload  # 新增代码+Phase29ComputerUse: 对外暴露观察 helper 类型；如果没有这行代码，测试和验收脚本需要硬编码内部模块路径。
from learning_agent.computer_use.lock import ComputerUseLockManager  # 新增代码+Phase30ComputerUseActionGate: 对外暴露 durable lock 管理器；如果没有这行代码，验收脚本无法方便获取和释放桌面控制锁。
from learning_agent.computer_use.models import ComputerUseWindowRef  # 新增代码+Phase27ComputerUse: 对外暴露强类型窗口引用；如果没有这行代码，后续 Windows 后端和测试只能从内部路径导入协议模型。
from learning_agent.computer_use.native_diagnostics import WindowsNativeObservationDiagnostics  # 新增代码+Phase33WindowsNativeDiagnostics: 对外暴露 native provider 诊断构建器；如果没有这行代码，验收和后续阶段需要硬编码内部模块路径。
from learning_agent.computer_use.native_helper import FallbackNativeWindowTextProvider, NativeWindowCaptureResult, NativeWindowTextResult, WindowsNativeWindowObservationHelper, WindowsUiautomationTextProvider, parse_hwnd_from_window  # 修改代码+Phase34WindowsUIAProvider: 对外暴露 UIA 文本 provider、fallback provider 和 native helper 类型；如果没有这行代码，测试和验收脚本需要硬编码内部模块路径。
from learning_agent.computer_use.real_uia_smoke import PHASE35_REAL_UIA_SMOKE_MARKER, PHASE35_REAL_UIA_SMOKE_OK_TOKEN, Phase35RealUiaSmokeResult, Phase35SafeWindowTarget, phase35_cli_line, phase35_dependency_status, run_phase35_real_uia_smoke  # 新增代码+Phase35WindowsRealUIASmoke: 对外暴露 Phase35 真实 UIA 安全窗口 smoke 入口；如果没有这行代码，后续验收和 Phase36-42 只能硬编码内部模块路径。
from learning_agent.computer_use.sendinput_executor import PHASE37_WINDOWS_SENDINPUT_EXECUTOR_MARKER, PHASE37_WINDOWS_SENDINPUT_EXECUTOR_OK_TOKEN, WindowsSendInputActionResult, WindowsSendInputExecutor, phase37_cli_line, run_phase37_sendinput_executor_contract  # 新增代码+Phase37WindowsSendInputExecutor: 对外暴露 Phase37 SendInput 执行器合同；如果没有这行代码，后续验收和状态诊断只能硬编码内部模块路径。
from learning_agent.computer_use.wgc_capture import PHASE36_WINDOWS_WGC_PROVIDER_MARKER, PHASE36_WINDOWS_WGC_PROVIDER_OK_TOKEN, WindowsGraphicsCaptureProvider, phase36_cli_line, phase36_dependency_status, run_phase36_wgc_provider_contract  # 新增代码+Phase36WindowsWGCProvider: 对外暴露 Phase36 Windows.Graphics.Capture provider 合同；如果没有这行代码，后续验收和 diagnostics 只能硬编码内部路径。
from learning_agent.computer_use.windows_backend import StaticWindowsWindowInventory, WindowsWindowInventoryProbe, WindowsWindowInventorySnapshot  # 新增代码+Phase28ComputerUse: 对外暴露只读窗口 inventory 类型；如果没有这行代码，后续阶段和学习测试无法方便复用 Phase 28 后端。
__all__ = ["COMPUTER_USE_OBSERVE_OPT_IN_ENV_VAR", "ComputerUseActionResult", "ComputerUseAuditStore", "ComputerUseController", "ComputerUseEvidenceStore", "ComputerUseLockManager", "ComputerUseWindowRef", "FallbackNativeWindowTextProvider", "FilteredAccessibilityText", "MemoryComputerUseBackend", "NativeWindowCaptureResult", "NativeWindowTextResult", "NullWindowObservationHelper", "PHASE35_REAL_UIA_SMOKE_MARKER", "PHASE35_REAL_UIA_SMOKE_OK_TOKEN", "PHASE36_WINDOWS_WGC_PROVIDER_MARKER", "PHASE36_WINDOWS_WGC_PROVIDER_OK_TOKEN", "PHASE37_WINDOWS_SENDINPUT_EXECUTOR_MARKER", "PHASE37_WINDOWS_SENDINPUT_EXECUTOR_OK_TOKEN", "PHASE38_WINDOWS_COMPUTER_APPROVAL_MARKER", "PHASE38_WINDOWS_COMPUTER_APPROVAL_OK_TOKEN", "POLICY_VERSION", "Phase35RealUiaSmokeResult", "Phase35SafeWindowTarget", "StaticWindowObservationHelper", "StaticWindowsWindowInventory", "UnavailableComputerUseBackend", "WindowObservationPayload", "WindowsComputerUseApprovalModel", "WindowsComputerUseBackend", "WindowsGraphicsCaptureProvider", "WindowsNativeObservationDiagnostics", "WindowsNativeWindowObservationHelper", "WindowsSendInputActionResult", "WindowsSendInputExecutor", "WindowsUiautomationTextProvider", "WindowsWindowInventoryProbe", "WindowsWindowInventorySnapshot", "build_action_evidence", "build_default_computer_use_backend", "parse_hwnd_from_window", "phase35_cli_line", "phase35_dependency_status", "phase36_cli_line", "phase36_dependency_status", "phase37_cli_line", "phase38_cli_line", "prepare_action_arguments", "redact_action_arguments", "run_phase35_real_uia_smoke", "run_phase36_wgc_provider_contract", "run_phase37_sendinput_executor_contract", "run_phase38_approval_contract"]  # 修改代码+Phase38WindowsComputerApproval: 限定公开导出名称并加入 Phase38 approval API；如果没有这行代码，from package import * 会遗漏审批模型和验收合同。
from learning_agent.computer_use.coordinates import PHASE39_COORDINATE_MODEL, PHASE39_WINDOWS_COORDINATES_MARKER, PHASE39_WINDOWS_COORDINATES_OK_TOKEN, build_coordinate_context, phase39_cli_line, run_phase39_coordinates_contract  # 新增代码+Phase39WindowsCoordinates: 追加公开导出 Phase39 坐标 API；如果没有这行代码，后续验收和阶段代码只能硬编码内部模块路径。
__all__.extend(["PHASE39_COORDINATE_MODEL", "PHASE39_WINDOWS_COORDINATES_MARKER", "PHASE39_WINDOWS_COORDINATES_OK_TOKEN", "build_coordinate_context", "phase39_cli_line", "run_phase39_coordinates_contract"])  # 新增代码+Phase39WindowsCoordinates: 追加 Phase39 导出名称到 __all__；如果没有这行代码，from learning_agent.computer_use import * 会漏掉坐标模型入口。
from learning_agent.computer_use.session_runtime import PHASE40_DEFAULT_SESSION_ID, PHASE40_SESSION_RUNTIME_MODEL, PHASE40_WINDOWS_ABORT_CLEANUP_MARKER, PHASE40_WINDOWS_ABORT_CLEANUP_OK_TOKEN, WindowsComputerUseSessionRuntime, format_phase40_runtime_action, phase40_cli_line, run_phase40_abort_cleanup_contract  # 新增代码+Phase40WindowsAbortCleanup: 追加公开导出 Phase40 runtime API；如果没有这行代码，后续验收和其他 agent 只能硬编码内部模块路径。
__all__.extend(["PHASE40_DEFAULT_SESSION_ID", "PHASE40_SESSION_RUNTIME_MODEL", "PHASE40_WINDOWS_ABORT_CLEANUP_MARKER", "PHASE40_WINDOWS_ABORT_CLEANUP_OK_TOKEN", "WindowsComputerUseSessionRuntime", "format_phase40_runtime_action", "phase40_cli_line", "run_phase40_abort_cleanup_contract"])  # 新增代码+Phase40WindowsAbortCleanup: 追加 Phase40 导出名称到 __all__；如果没有这行代码，from learning_agent.computer_use import * 会漏掉会话运行时入口。
from learning_agent.computer_use.evidence import PHASE41_ACTIONS_EXPANDED, PHASE41_IMAGE_RESULT_MODEL, PHASE41_WINDOWS_IMAGE_RESULTS_MARKER, PHASE41_WINDOWS_IMAGE_RESULTS_OK_TOKEN, build_image_result_blocks, collect_image_result_blocks, format_image_result_lines, phase41_cli_line, run_phase41_image_results_contract, screenshot_mime_type  # 新增代码+Phase41WindowsImageResults: 追加公开导出 Phase41 图片结果协议 API；如果没有这行代码，后续验收和其它模块只能硬编码 evidence 内部路径。
__all__.extend(["PHASE41_ACTIONS_EXPANDED", "PHASE41_IMAGE_RESULT_MODEL", "PHASE41_WINDOWS_IMAGE_RESULTS_MARKER", "PHASE41_WINDOWS_IMAGE_RESULTS_OK_TOKEN", "build_image_result_blocks", "collect_image_result_blocks", "format_image_result_lines", "phase41_cli_line", "run_phase41_image_results_contract", "screenshot_mime_type"])  # 新增代码+Phase41WindowsImageResults: 把 Phase41 图片协议名称加入 __all__；如果没有这行代码，from learning_agent.computer_use import * 会漏掉图片结果能力。
from learning_agent.computer_use.final_matrix import PHASE42_MATRIX_MODEL, PHASE42_WINDOWS_COMPUTER_USE_FINAL_MARKER, PHASE42_WINDOWS_COMPUTER_USE_FINAL_OK_TOKEN, load_phase42_final_matrix, phase42_cli_line, run_phase42_final_matrix_contract  # 新增代码+Phase42WindowsFinalMatrix: 追加公开导出 Phase42 最终矩阵 API；如果没有这行代码，最终验收和后续 agent 只能硬编码内部模块路径。
__all__.extend(["PHASE42_MATRIX_MODEL", "PHASE42_WINDOWS_COMPUTER_USE_FINAL_MARKER", "PHASE42_WINDOWS_COMPUTER_USE_FINAL_OK_TOKEN", "load_phase42_final_matrix", "phase42_cli_line", "run_phase42_final_matrix_contract"])  # 新增代码+Phase42WindowsFinalMatrix: 把 Phase42 最终矩阵名称加入 __all__；如果没有这行代码，包级导入会漏掉最终验收入口。
from learning_agent.computer_use.real_screenshot_pipeline import PHASE56_REAL_SCREENSHOT_MODEL, PHASE56_WINDOWS_REAL_SCREENSHOT_MARKER, PHASE56_WINDOWS_REAL_SCREENSHOT_OK_TOKEN, Phase56PixelGuard, WindowsRealScreenshotPipeline, phase56_cli_line, run_phase56_real_screenshot_pipeline_contract  # 新增代码+Phase56RealScreenshotPipeline: 追加公开导出 Phase56 真实截图和像素守卫 API；如果没有这行代码，后续验收和其他 agent 只能硬编码内部模块路径。
__all__.extend(["PHASE56_REAL_SCREENSHOT_MODEL", "PHASE56_WINDOWS_REAL_SCREENSHOT_MARKER", "PHASE56_WINDOWS_REAL_SCREENSHOT_OK_TOKEN", "Phase56PixelGuard", "WindowsRealScreenshotPipeline", "phase56_cli_line", "run_phase56_real_screenshot_pipeline_contract"])  # 新增代码+Phase56RealScreenshotPipeline: 把 Phase56 名称加入 __all__；如果没有这行代码，from learning_agent.computer_use import * 会漏掉真实截图 pipeline。
from learning_agent.computer_use.real_uia_locator import PHASE57_REAL_UIA_LOCATOR_MODEL, PHASE57_WINDOWS_REAL_UIA_LOCATOR_MARKER, PHASE57_WINDOWS_REAL_UIA_LOCATOR_OK_TOKEN, PowerShellUiaTreeProvider, SemanticControlLocator, WindowsRealUiaLocatorRuntime, phase57_cli_line, run_phase57_real_uia_locator_contract, run_phase57_real_uia_locator_smoke  # 新增代码+Phase57RealUiaLocator: 追加公开导出 Phase57 真实 UIA 树和语义定位 API；如果没有这行代码，后续验收和其他 agent 只能硬编码内部模块路径。
__all__.extend(["PHASE57_REAL_UIA_LOCATOR_MODEL", "PHASE57_WINDOWS_REAL_UIA_LOCATOR_MARKER", "PHASE57_WINDOWS_REAL_UIA_LOCATOR_OK_TOKEN", "PowerShellUiaTreeProvider", "SemanticControlLocator", "WindowsRealUiaLocatorRuntime", "phase57_cli_line", "run_phase57_real_uia_locator_contract", "run_phase57_real_uia_locator_smoke"])  # 新增代码+Phase57RealUiaLocator: 把 Phase57 名称加入 __all__；如果没有这行代码，from learning_agent.computer_use import * 会漏掉真实 UIA locator。
