"""Computer Use package exports."""  # 修改代码+URG3ActionDSL：说明本文件只负责包级公开 API；如果没有这一行，读者不容易区分导出文件和业务实现文件。
from learning_agent.computer_use.mode_session import DEFAULT_MODE_SESSION_ID, DEFAULT_MODE_SESSION_ROOT, PHASE98_COMPUTER_USE_MODE_MODEL, PHASE98_COMPUTER_USE_MODE_OK, PHASE98_COMPUTER_USE_MODE_READY, ComputerUseModeSessionStore  # 修改代码+URG3ActionDSL：保留 Phase98 full mode session 导出；如果没有这一行，已有 /computer use 会话状态调用会断。
from learning_agent.computer_use.universal_action_dsl import PHASE118_ACTIONS_EXPANDED, PHASE118_REAL_DISPATCH_PERFORMED, PHASE118_UNIVERSAL_ACTION_DSL_MARKER, PHASE118_UNIVERSAL_ACTION_DSL_MODEL, PHASE118_UNIVERSAL_ACTION_DSL_OK_TOKEN, Phase118RecordingLowLevelSender, UniversalActionDslRuntime, phase118_universal_action_dsl_cli_line, run_phase118_universal_action_dsl_contract  # 新增代码+URG3ActionDSL：导出 URG-3 通用动作 DSL 桥 API；如果没有这一行，外部模块只能硬编码内部文件路径。
from learning_agent.computer_use.universal_live_execution import UniversalWindowsLiveExecutionGate  # 修改代码+URG3ActionDSL：保留 Phase93/102 通用 live execution gate 导出；如果没有这一行，已有通用执行门禁调用会断。
from learning_agent.computer_use.universal_real_observation import PHASE116_ACTIONS_EXPANDED, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MARKER, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MODEL, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_OK_TOKEN, UniversalRealObservationFrameRuntime, run_universal_real_observation_frame_contract, universal_real_observation_frame_cli_line  # 修改代码+URG3ActionDSL：保留 URG-1 真实观察帧 API 导出；如果没有这一行，外部模块拿不到观察帧入口。
from learning_agent.computer_use.universal_target_session import PHASE117_ACTIONS_EXPANDED, PHASE117_UNIVERSAL_TARGET_SESSION_MARKER, PHASE117_UNIVERSAL_TARGET_SESSION_MODEL, PHASE117_UNIVERSAL_TARGET_SESSION_OK_TOKEN, UniversalTargetSessionRuntime, phase117_universal_target_session_cli_line, run_phase117_universal_target_session_contract  # 新增代码+URG3ActionDSL：导出 URG-2 通用目标 session API；如果没有这一行，动作 DSL 的上游凭证能力无法从包级入口访问。

__all__: list[str] = []  # 修改代码+URG3ActionDSL：初始化公开名称列表；如果没有这一行，后续 extend 会因为变量不存在而失败。
__all__.extend(["DEFAULT_MODE_SESSION_ID", "DEFAULT_MODE_SESSION_ROOT", "PHASE98_COMPUTER_USE_MODE_MODEL", "PHASE98_COMPUTER_USE_MODE_OK", "PHASE98_COMPUTER_USE_MODE_READY", "ComputerUseModeSessionStore"])  # 修改代码+URG3ActionDSL：公开 Phase98 session 名称；如果没有这一行，老的包级导入回归会失败。
__all__.extend(["UniversalWindowsLiveExecutionGate"])  # 修改代码+URG3ActionDSL：公开通用 live execution gate；如果没有这一行，已有 Phase93/102 API 会从包级导出消失。
__all__.extend(["PHASE116_ACTIONS_EXPANDED", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MARKER", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MODEL", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_OK_TOKEN", "UniversalRealObservationFrameRuntime", "run_universal_real_observation_frame_contract", "universal_real_observation_frame_cli_line"])  # 修改代码+URG3ActionDSL：公开 URG-1 观察帧名称；如果没有这一行，通配导入会漏掉观察能力。
__all__.extend(["PHASE117_ACTIONS_EXPANDED", "PHASE117_UNIVERSAL_TARGET_SESSION_MARKER", "PHASE117_UNIVERSAL_TARGET_SESSION_MODEL", "PHASE117_UNIVERSAL_TARGET_SESSION_OK_TOKEN", "UniversalTargetSessionRuntime", "phase117_universal_target_session_cli_line", "run_phase117_universal_target_session_contract"])  # 新增代码+URG3ActionDSL：公开 URG-2 目标 session 名称；如果没有这一行，通配导入会漏掉目标身份门禁能力。
__all__.extend(["PHASE118_ACTIONS_EXPANDED", "PHASE118_REAL_DISPATCH_PERFORMED", "PHASE118_UNIVERSAL_ACTION_DSL_MARKER", "PHASE118_UNIVERSAL_ACTION_DSL_MODEL", "PHASE118_UNIVERSAL_ACTION_DSL_OK_TOKEN", "Phase118RecordingLowLevelSender", "UniversalActionDslRuntime", "phase118_universal_action_dsl_cli_line", "run_phase118_universal_action_dsl_contract"])  # 新增代码+URG3ActionDSL：公开 URG-3 动作 DSL 桥名称；如果没有这一行，通配导入会漏掉新动作桥。
