"""Computer Use package exports."""  # 修改代码+URG1RealObservationFrame：说明本文件只负责包级公开 API；如果没有这一行，读者不容易区分入口导出和业务逻辑。
from learning_agent.computer_use.mode_session import DEFAULT_MODE_SESSION_ID, DEFAULT_MODE_SESSION_ROOT, PHASE98_COMPUTER_USE_MODE_MODEL, PHASE98_COMPUTER_USE_MODE_OK, PHASE98_COMPUTER_USE_MODE_READY, ComputerUseModeSessionStore  # 修改代码+URG1RealObservationFrame：保留 Phase98 通用 Computer Use session 导出；如果没有这一行，既有 full mode session 调用会断。
from learning_agent.computer_use.universal_live_execution import UniversalWindowsLiveExecutionGate  # 修改代码+URG1RealObservationFrame：保留 Phase93/102 通用 live execution gate 导出；如果没有这一行，既有通用执行门禁调用会断。
from learning_agent.computer_use.universal_real_observation import PHASE116_ACTIONS_EXPANDED, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MARKER, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MODEL, PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_OK_TOKEN, UniversalRealObservationFrameRuntime, run_universal_real_observation_frame_contract, universal_real_observation_frame_cli_line  # 新增代码+URG1RealObservationFrame：导出 URG-1 真实观察帧 API；如果没有这一行，外部模块只能硬编码内部模块路径。

__all__: list[str] = []  # 修改代码+URG1RealObservationFrame：初始化包级公开名称列表；如果没有这一行，后续 extend 会因变量不存在而失败。
__all__.extend(["DEFAULT_MODE_SESSION_ID", "DEFAULT_MODE_SESSION_ROOT", "PHASE98_COMPUTER_USE_MODE_MODEL", "PHASE98_COMPUTER_USE_MODE_OK", "PHASE98_COMPUTER_USE_MODE_READY", "ComputerUseModeSessionStore"])  # 修改代码+URG1RealObservationFrame：公开 Phase98 session 名称；如果没有这一行，老的包级导入回归会失败。
__all__.extend(["UniversalWindowsLiveExecutionGate"])  # 修改代码+URG1RealObservationFrame：公开通用 live execution gate；如果没有这一行，既有 Phase93 API 会从包级导出消失。
__all__.extend(["PHASE116_ACTIONS_EXPANDED", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MARKER", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_MODEL", "PHASE116_UNIVERSAL_REAL_OBSERVATION_FRAME_OK_TOKEN", "UniversalRealObservationFrameRuntime", "run_universal_real_observation_frame_contract", "universal_real_observation_frame_cli_line"])  # 新增代码+URG1RealObservationFrame：公开 URG-1 观察帧名称；如果没有这一行，`from learning_agent.computer_use import *` 会漏掉新能力。
