"""Windows Computer Use Phase64 最终 parity-plus 生产矩阵。"""  # 新增代码+Phase64ParityPlusMatrix: 标明本文件负责汇总 Phase53-63 的最终生产门禁；如果没有这行代码，读者不知道最终验收入口在哪里。
from __future__ import annotations  # 新增代码+Phase64ParityPlusMatrix: 启用延迟类型解析；如果没有这行代码，旧运行路径遇到前向类型标注时更容易导入失败。

import json  # 新增代码+Phase64ParityPlusMatrix: 导入 JSON 用于 CLI 打印结构化报告；如果没有这行代码，失败时不容易复盘每个阶段的明细。
from pathlib import Path  # 新增代码+Phase64ParityPlusMatrix: 导入 Path 统一处理 Windows 路径；如果没有这行代码，memory、scenario 和临时目录路径容易拼错。
from typing import Any  # 新增代码+Phase64ParityPlusMatrix: 导入 Any 描述各阶段动态报告；如果没有这行代码，函数边界缺少清晰的类型提示。

PHASE64_WINDOWS_PARITY_PLUS_MATRIX_MARKER = "PHASE64_WINDOWS_PARITY_PLUS_MATRIX_READY"  # 新增代码+Phase64ParityPlusMatrix: 定义 Phase64 ready marker；如果没有这行代码，真实终端验收没有稳定锚点。
PHASE64_WINDOWS_PARITY_PLUS_MATRIX_OK_TOKEN = "PHASE64_WINDOWS_PARITY_PLUS_MATRIX_OK"  # 新增代码+Phase64ParityPlusMatrix: 定义 Phase64 OK token；如果没有这行代码，debug log 无法区分最终矩阵通过和普通输出。
PHASE64_PARITY_PLUS_MATRIX_MODEL = "phase64_windows_parity_plus_production_matrix"  # 新增代码+Phase64ParityPlusMatrix: 定义最终矩阵模型名；如果没有这行代码，报告无法说明当前使用哪套验收规则。
PHASE64_EXPECTED_PHASE_COUNT = 11  # 新增代码+Phase64ParityPlusMatrix: 固定 Phase53-63 共十一个已实现阶段；如果没有这行代码，漏跑阶段也可能被误判为完整。
PHASE64_ACTIONS_EXPANDED = False  # 新增代码+Phase64ParityPlusMatrix: 明确 Phase64 自身不新增真实桌面动作；如果没有这行代码，用户可能误以为最终矩阵会直接控制电脑。
PHASE64_EXPECTED_PHASE_IDS = ("53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63")  # 新增代码+Phase64ParityPlusMatrix: 固定最终矩阵必须覆盖的阶段编号；如果没有这行代码，阶段顺序和数量会漂移。
PHASE64_PHASE_LABELS = {"53": "phase53_parity_gap", "54": "phase54_native_reality_gate", "55": "phase55_native_helper_v2", "56": "phase56_real_screenshot_pipeline", "57": "phase57_real_uia_locator", "58": "phase58_real_sendinput_guard", "59": "phase59_session_context", "60": "phase60_persistent_grants", "61": "phase61_abort_streaming_hooks", "62": "phase62_high_level_tools", "63": "phase63_controller_takeover"}  # 新增代码+Phase64ParityPlusMatrix: 定义 CLI token 使用的稳定阶段名称；如果没有这行代码，真实终端断言容易和内部文件名混在一起。
DEFAULT_PHASE64_PARITY_PLUS_MATRIX_ROOT = Path(__file__).resolve().parents[1] / "memory" / "computer_use" / "parity_plus_matrix"  # 新增代码+Phase64ParityPlusMatrix: 定义默认证据目录；如果没有这行代码，CLI 自检没有稳定落盘位置。
DEFAULT_PHASE64_SCENARIO_PATH = Path(__file__).resolve().parents[1] / "acceptance_controller" / "scenarios" / "agent_capability_phase64_parity_plus_matrix.json"  # 新增代码+Phase64ParityPlusMatrix: 定义真实可见终端场景路径；如果没有这行代码，总矩阵无法把场景文件也纳入门禁。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，_bool_token 把布尔值转成验收器稳定匹配的小写 token；如果没有这段函数，CLI 输出可能混用 True/False 和 true/false，作者意图是让真实终端断言稳定。
def _bool_token(value: Any) -> str:  # 新增代码+Phase64ParityPlusMatrix: 定义布尔 token helper；如果没有这行代码，多处输出会重复写转换逻辑。
    return "true" if bool(value) else "false"  # 新增代码+Phase64ParityPlusMatrix: 返回小写布尔文本；如果没有这行代码，场景 JSON 的 token 匹配可能失败。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，_bool_token 到此结束；如果没有这个边界说明，初学者不容易看出布尔格式化范围。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，_phase64_import_contracts 延迟导入 Phase53-63 合同；如果没有这段函数，模块导入时会急切加载所有阶段并增加循环依赖风险，作者意图是只在总验收运行时加载依赖。
def _phase64_import_contracts() -> dict[str, Any]:  # 新增代码+Phase64ParityPlusMatrix: 定义合同导入 helper；如果没有这行代码，run 函数会堆满重复导入代码。
    try:  # 新增代码+Phase64ParityPlusMatrix: 优先使用 learning_agent 包模式导入；如果没有这行代码，正常 unittest 和项目根目录运行时无法加载阶段合同。
        from learning_agent.computer_use.abort_streaming_hooks import phase61_cli_line, run_phase61_abort_streaming_hooks_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase61 abort/streaming 合同；如果没有这行代码，总矩阵无法覆盖中断清理。
        from learning_agent.computer_use.controller_takeover import phase63_cli_line, run_phase63_controller_takeover_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase63 controller takeover 合同；如果没有这行代码，总矩阵无法覆盖外部 agent 接管面。
        from learning_agent.computer_use.high_level_tools import phase62_cli_line, run_phase62_high_level_tools_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase62 高层工具合同；如果没有这行代码，总矩阵无法覆盖工具 API。
        from learning_agent.computer_use.native_helper_v2 import phase55_cli_line, run_phase55_native_helper_v2_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase55 helper v2 合同；如果没有这行代码，总矩阵无法覆盖 out-of-process helper。
        from learning_agent.computer_use.native_reality_gate import phase54_cli_line, run_phase54_native_reality_gate_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase54 原生现实门禁合同；如果没有这行代码，总矩阵无法覆盖依赖和权限现实检查。
        from learning_agent.computer_use.parity_gap_matrix import phase53_cli_line, run_phase53_parity_gap_matrix_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase53 差距矩阵合同；如果没有这行代码，总矩阵无法证明非 fake 验收基线。
        from learning_agent.computer_use.persistent_grants import phase60_cli_line, run_phase60_persistent_grants_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase60 持久授权合同；如果没有这行代码，总矩阵无法覆盖审批和授权链。
        from learning_agent.computer_use.real_screenshot_pipeline import phase56_cli_line, run_phase56_real_screenshot_pipeline_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase56 真实截图合同；如果没有这行代码，总矩阵无法覆盖像素守卫和 artifact。
        from learning_agent.computer_use.real_sendinput_guard import phase58_cli_line, run_phase58_real_sendinput_guard_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase58 真实 SendInput 守卫合同；如果没有这行代码，总矩阵无法覆盖受控真实动作路径。
        from learning_agent.computer_use.real_uia_locator import phase57_cli_line, run_phase57_real_uia_locator_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase57 真实 UIA locator 合同；如果没有这行代码，总矩阵无法覆盖控件树和语义定位。
        from learning_agent.computer_use.session_context import phase59_cli_line, run_phase59_session_context_contract  # 新增代码+Phase64ParityPlusMatrix: 导入 Phase59 session context 合同；如果没有这行代码，总矩阵无法覆盖 AppState 持久化。
    except ModuleNotFoundError as error:  # 新增代码+Phase64ParityPlusMatrix: 兼容 start_oauth_agent.bat 从 learning_agent 目录运行时的脚本模式；如果没有这行代码，真实终端入口可能导入失败。
        if error.name not in {"learning_agent", "learning_agent.computer_use", "learning_agent.computer_use.abort_streaming_hooks", "learning_agent.computer_use.controller_takeover", "learning_agent.computer_use.high_level_tools", "learning_agent.computer_use.native_helper_v2", "learning_agent.computer_use.native_reality_gate", "learning_agent.computer_use.parity_gap_matrix", "learning_agent.computer_use.persistent_grants", "learning_agent.computer_use.real_screenshot_pipeline", "learning_agent.computer_use.real_sendinput_guard", "learning_agent.computer_use.real_uia_locator", "learning_agent.computer_use.session_context"}:  # 新增代码+Phase64ParityPlusMatrix: 只允许目标包路径缺失时 fallback；如果没有这行代码，真实内部 bug 会被误吞。
            raise  # 新增代码+Phase64ParityPlusMatrix: 重新抛出非路径类导入错误；如果没有这行代码，排查阶段合同 bug 会很困难。
        from computer_use.abort_streaming_hooks import phase61_cli_line, run_phase61_abort_streaming_hooks_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase61 合同；如果没有这行代码，bat 入口无法运行 abort/streaming 总验收。
        from computer_use.controller_takeover import phase63_cli_line, run_phase63_controller_takeover_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase63 合同；如果没有这行代码，bat 入口无法运行 controller takeover 总验收。
        from computer_use.high_level_tools import phase62_cli_line, run_phase62_high_level_tools_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase62 合同；如果没有这行代码，bat 入口无法运行高层工具总验收。
        from computer_use.native_helper_v2 import phase55_cli_line, run_phase55_native_helper_v2_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase55 合同；如果没有这行代码，bat 入口无法运行 helper v2 总验收。
        from computer_use.native_reality_gate import phase54_cli_line, run_phase54_native_reality_gate_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase54 合同；如果没有这行代码，bat 入口无法运行现实门禁总验收。
        from computer_use.parity_gap_matrix import phase53_cli_line, run_phase53_parity_gap_matrix_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase53 合同；如果没有这行代码，bat 入口无法运行差距矩阵总验收。
        from computer_use.persistent_grants import phase60_cli_line, run_phase60_persistent_grants_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase60 合同；如果没有这行代码，bat 入口无法运行持久授权总验收。
        from computer_use.real_screenshot_pipeline import phase56_cli_line, run_phase56_real_screenshot_pipeline_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase56 合同；如果没有这行代码，bat 入口无法运行截图总验收。
        from computer_use.real_sendinput_guard import phase58_cli_line, run_phase58_real_sendinput_guard_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase58 合同；如果没有这行代码，bat 入口无法运行 SendInput 总验收。
        from computer_use.real_uia_locator import phase57_cli_line, run_phase57_real_uia_locator_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase57 合同；如果没有这行代码，bat 入口无法运行 UIA locator 总验收。
        from computer_use.session_context import phase59_cli_line, run_phase59_session_context_contract  # 新增代码+Phase64ParityPlusMatrix: 脚本模式导入 Phase59 合同；如果没有这行代码，bat 入口无法运行 session context 总验收。
    return {"phase53_cli_line": phase53_cli_line, "run_phase53_parity_gap_matrix_contract": run_phase53_parity_gap_matrix_contract, "phase54_cli_line": phase54_cli_line, "run_phase54_native_reality_gate_contract": run_phase54_native_reality_gate_contract, "phase55_cli_line": phase55_cli_line, "run_phase55_native_helper_v2_contract": run_phase55_native_helper_v2_contract, "phase56_cli_line": phase56_cli_line, "run_phase56_real_screenshot_pipeline_contract": run_phase56_real_screenshot_pipeline_contract, "phase57_cli_line": phase57_cli_line, "run_phase57_real_uia_locator_contract": run_phase57_real_uia_locator_contract, "phase58_cli_line": phase58_cli_line, "run_phase58_real_sendinput_guard_contract": run_phase58_real_sendinput_guard_contract, "phase59_cli_line": phase59_cli_line, "run_phase59_session_context_contract": run_phase59_session_context_contract, "phase60_cli_line": phase60_cli_line, "run_phase60_persistent_grants_contract": run_phase60_persistent_grants_contract, "phase61_cli_line": phase61_cli_line, "run_phase61_abort_streaming_hooks_contract": run_phase61_abort_streaming_hooks_contract, "phase62_cli_line": phase62_cli_line, "run_phase62_high_level_tools_contract": run_phase62_high_level_tools_contract, "phase63_cli_line": phase63_cli_line, "run_phase63_controller_takeover_contract": run_phase63_controller_takeover_contract}  # 新增代码+Phase64ParityPlusMatrix: 返回所有阶段合同入口；如果没有这行代码，调用方无法统一执行 Phase53-63 自检。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，_phase64_import_contracts 到此结束；如果没有这个边界说明，初学者不容易看出导入兼容层范围。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，_phase64_phase_summary 把单阶段报告压缩成总矩阵需要的安全摘要；如果没有这段函数，报告会重复拼字段且难以定位失败阶段，作者意图是给外部 agent 一个清晰事实源。
def _phase64_phase_summary(phase_id: str, report: dict[str, Any]) -> dict[str, Any]:  # 新增代码+Phase64ParityPlusMatrix: 定义阶段摘要 helper；如果没有这行代码，phase_results 结构不稳定。
    return {"phase_id": phase_id, "label": PHASE64_PHASE_LABELS.get(phase_id, phase_id), "marker": str(report.get("marker", "")), "ok_token": str(report.get("ok_token", "")), "passed": bool(report.get("passed", False)), "actions_expanded": bool(report.get("actions_expanded", False)), "state_dir": str(report.get("state_dir", ""))}  # 新增代码+Phase64ParityPlusMatrix: 返回稳定阶段摘要；如果没有这行代码，外部 agent 无法快速知道哪个阶段失败。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，_phase64_phase_summary 到此结束；如果没有这个边界说明，初学者不容易看出阶段摘要范围。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，run_phase64_parity_plus_matrix_contract 汇总 Phase53-63 最终合同；如果没有这段函数，Phase64 只会停留在文档，作者意图是让自动化和真实终端共用同一总门禁。
def run_phase64_parity_plus_matrix_contract(base_dir: str | Path | None = None) -> dict[str, Any]:  # 新增代码+Phase64ParityPlusMatrix: 定义 Phase64 总合同入口；如果没有这行代码，测试和终端场景没有统一自检函数。
    root = Path(base_dir) if base_dir is not None else DEFAULT_PHASE64_PARITY_PLUS_MATRIX_ROOT  # 新增代码+Phase64ParityPlusMatrix: 选择传入目录或默认目录；如果没有这行代码，测试无法隔离证据目录。
    root.mkdir(parents=True, exist_ok=True)  # 新增代码+Phase64ParityPlusMatrix: 创建总矩阵证据目录；如果没有这行代码，Phase54/59/60/61/62/63 的子目录写入可能失败。
    contracts = _phase64_import_contracts()  # 新增代码+Phase64ParityPlusMatrix: 加载所有阶段合同；如果没有这行代码，后续无法调用 Phase53-63 自检。
    phase53_report = contracts["run_phase53_parity_gap_matrix_contract"]()  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase53 差距矩阵；如果没有这行代码，总矩阵无法证明非 fake 验收蓝图仍完整。
    phase54_report = contracts["run_phase54_native_reality_gate_contract"](output_root=root / "phase54")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase54 原生现实门禁并写入隔离目录；如果没有这行代码，总矩阵无法证明依赖检查没有自动安装或改设置。
    phase55_report = contracts["run_phase55_native_helper_v2_contract"]()  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase55 helper v2 合同；如果没有这行代码，总矩阵无法证明 out-of-process helper 仍可用。
    phase56_report = contracts["run_phase56_real_screenshot_pipeline_contract"](real_smoke=False)  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase56 合同但不额外打开真实桌面 smoke；如果没有这行代码，总矩阵可能扩大验收动作面。
    phase57_report = contracts["run_phase57_real_uia_locator_contract"](real_smoke=False)  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase57 合同但不额外打开真实 UIA smoke；如果没有这行代码，总矩阵可能触碰真实窗口。
    phase58_report = contracts["run_phase58_real_sendinput_guard_contract"](real_smoke=False)  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase58 合同但不额外发送真实输入 smoke；如果没有这行代码，总矩阵可能在最终验收里扩大真实输入动作。
    phase59_report = contracts["run_phase59_session_context_contract"](base_dir=root / "phase59")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase59 session context 合同；如果没有这行代码，总矩阵无法证明 AppState 持久化仍可用。
    phase60_report = contracts["run_phase60_persistent_grants_contract"](base_dir=root / "phase60")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase60 持久授权合同；如果没有这行代码，总矩阵无法证明审批链和默认拒绝仍可用。
    phase61_report = contracts["run_phase61_abort_streaming_hooks_contract"](base_dir=root / "phase61")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase61 abort/streaming 合同；如果没有这行代码，总矩阵无法证明中断清理链仍可用。
    phase62_report = contracts["run_phase62_high_level_tools_contract"](base_dir=root / "phase62")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase62 高层工具合同；如果没有这行代码，总矩阵无法证明工具 API 和 streaming 仍可用。
    phase63_report = contracts["run_phase63_controller_takeover_contract"](base_dir=root / "phase63")  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase63 controller takeover 合同；如果没有这行代码，总矩阵无法证明外部 agent 接管面仍可用。
    phase_reports = {"53": phase53_report, "54": phase54_report, "55": phase55_report, "56": phase56_report, "57": phase57_report, "58": phase58_report, "59": phase59_report, "60": phase60_report, "61": phase61_report, "62": phase62_report, "63": phase63_report}  # 新增代码+Phase64ParityPlusMatrix: 汇总原始阶段报告；如果没有这行代码，失败时不知道哪一阶段掉链子。
    phase_cli_lines = {"53": contracts["phase53_cli_line"](phase53_report), "54": contracts["phase54_cli_line"](phase54_report), "55": contracts["phase55_cli_line"](phase55_report), "56": contracts["phase56_cli_line"](phase56_report), "57": contracts["phase57_cli_line"](phase57_report), "58": contracts["phase58_cli_line"](phase58_report), "59": contracts["phase59_cli_line"](phase59_report), "60": contracts["phase60_cli_line"](phase60_report), "61": contracts["phase61_cli_line"](phase61_report), "62": contracts["phase62_cli_line"](phase62_report), "63": contracts["phase63_cli_line"](phase63_report)}  # 新增代码+Phase64ParityPlusMatrix: 收集每个阶段稳定 CLI token 行；如果没有这行代码，总矩阵缺少可审计输出证据。
    phase_results = {phase_id: _phase64_phase_summary(phase_id, phase_reports[phase_id]) for phase_id in PHASE64_EXPECTED_PHASE_IDS}  # 新增代码+Phase64ParityPlusMatrix: 生成压缩阶段摘要；如果没有这行代码，外部 agent 需要解析庞大原始报告。
    phase53_parity_gap = bool(phase53_report.get("passed") and phase53_report.get("owner_phases_complete") and phase53_report.get("non_fake_acceptance_contract"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase53 差距锁定是否成立；如果没有这行代码，非 fake 验收基线可能脱落。
    phase54_native_reality_gate = bool(phase54_report.get("passed") and int(phase54_report.get("dependency_count", 0) or 0) == 9 and not phase54_report.get("install_attempted") and not phase54_report.get("system_settings_changed"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase54 现实门禁是否成立；如果没有这行代码，自动安装或改系统设置的风险不会进入总门禁。
    phase55_native_helper_v2 = bool(phase55_report.get("passed") and phase55_report.get("process_started") and phase55_report.get("health") and phase55_report.get("crash_handled"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase55 helper v2 是否成立；如果没有这行代码，进程隔离和崩溃恢复可能漏验。
    phase56_real_screenshot_pipeline = bool(phase56_report.get("passed") and phase56_report.get("pixel_guard") and phase56_report.get("artifact") and phase56_report.get("raw_bytes_hidden"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase56 截图 pipeline 是否成立；如果没有这行代码，空截图或泄露原始字节可能漏验。
    phase57_real_uia_locator = bool(phase57_report.get("passed") and phase57_report.get("real_uia_tree") and phase57_report.get("semantic_locator") and phase57_report.get("raw_text_hidden"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase57 UIA locator 是否成立；如果没有这行代码，控件树和脱敏可能漏验。
    phase58_real_sendinput_guard = bool(phase58_report.get("passed") and phase58_report.get("target_guard") and phase58_report.get("forbidden_zero_events") and phase58_report.get("safe_window_only") and phase58_report.get("raw_text_hidden"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase58 真实输入守卫是否成立；如果没有这行代码，受控 SendInput 能力可能被误判。
    phase59_session_context = bool(phase59_report.get("passed") and phase59_report.get("context_persisted") and phase59_report.get("multi_session_isolated") and phase59_report.get("cleanup_state"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase59 会话上下文是否成立；如果没有这行代码，AppState 隔离和清理可能漏验。
    phase60_persistent_grants = bool(phase60_report.get("passed") and phase60_report.get("approve") and phase60_report.get("unauthorized_denied") and phase60_report.get("high_risk_default"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase60 持久授权是否成立；如果没有这行代码，审批和高风险默认拒绝可能漏验。
    phase61_abort_streaming_hooks = bool(phase61_report.get("passed") and phase61_report.get("abort_zero_events") and phase61_report.get("exception_cleanup") and phase61_report.get("streaming_hooks"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase61 中断和 streaming hooks 是否成立；如果没有这行代码，异常清理和中断零副作用可能漏验。
    phase62_high_level_tools = bool(phase62_report.get("passed") and phase62_report.get("high_level_ops") and phase62_report.get("read_only_parallel") and phase62_report.get("abort_zero_events"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase62 高层工具是否成立；如果没有这行代码，只读并行和写动作串行可能漏验。
    phase63_controller_takeover = bool(phase63_report.get("passed") and phase63_report.get("launches_visible_terminal") and phase63_report.get("reads_acceptance_run") and phase63_report.get("approval_bypass_blocked"))  # 新增代码+Phase64ParityPlusMatrix: 判断 Phase63 外部接管是否成立；如果没有这行代码，controller 可能绕过真实终端或审批。
    phase_flags = {"phase53_parity_gap": phase53_parity_gap, "phase54_native_reality_gate": phase54_native_reality_gate, "phase55_native_helper_v2": phase55_native_helper_v2, "phase56_real_screenshot_pipeline": phase56_real_screenshot_pipeline, "phase57_real_uia_locator": phase57_real_uia_locator, "phase58_real_sendinput_guard": phase58_real_sendinput_guard, "phase59_session_context": phase59_session_context, "phase60_persistent_grants": phase60_persistent_grants, "phase61_abort_streaming_hooks": phase61_abort_streaming_hooks, "phase62_high_level_tools": phase62_high_level_tools, "phase63_controller_takeover": phase63_controller_takeover}  # 新增代码+Phase64ParityPlusMatrix: 汇总每个阶段的最终布尔门禁；如果没有这行代码，CLI token 需要散落读取多个局部变量。
    phase_count = len(phase_results)  # 新增代码+Phase64ParityPlusMatrix: 计算实际覆盖阶段数；如果没有这行代码，少跑阶段无法进入总判断。
    all_phase_contracts_passed = bool(phase_count == PHASE64_EXPECTED_PHASE_COUNT and all(phase_flags.values()) and all(bool(phase_results[phase_id]["passed"]) for phase_id in PHASE64_EXPECTED_PHASE_IDS))  # 新增代码+Phase64ParityPlusMatrix: 判断所有阶段合同是否通过；如果没有这行代码，总矩阵可能只看部分高层字段。
    non_fake_acceptance = bool(phase53_report.get("non_fake_acceptance_contract") and phase53_report.get("real_provider_required"))  # 新增代码+Phase64ParityPlusMatrix: 汇总非 fake 验收门禁；如果没有这行代码，最终矩阵无法证明真实 provider 要求仍存在。
    visible_terminal_gate = bool(DEFAULT_PHASE64_SCENARIO_PATH.exists() and phase63_report.get("visible_terminal_required") and phase63_report.get("launches_visible_terminal"))  # 新增代码+Phase64ParityPlusMatrix: 汇总真实可见终端门禁；如果没有这行代码，场景 JSON 缺失也可能被误判为完成。
    approval_bypass_blocked = bool(phase60_report.get("high_risk_default") and phase63_report.get("approval_bypass_blocked") and not phase63_report.get("actions_expanded"))  # 新增代码+Phase64ParityPlusMatrix: 汇总审批绕过阻断；如果没有这行代码，外部 controller 的越权风险不会进入总门禁。
    controlled_actions_expansion = bool(phase58_report.get("actions_expanded") and phase58_real_sendinput_guard and phase60_persistent_grants and phase61_abort_streaming_hooks)  # 新增代码+Phase64ParityPlusMatrix: 识别 Phase58 受控真实动作扩展；如果没有这行代码，最终矩阵会把安全 SendInput 能力误报为危险扩张。
    non_phase58_actions_expanded = any(bool(phase_reports[phase_id].get("actions_expanded", False)) for phase_id in PHASE64_EXPECTED_PHASE_IDS if phase_id != "58")  # 新增代码+Phase64ParityPlusMatrix: 检查除 Phase58 外是否有阶段扩张动作面；如果没有这行代码，非预期动作扩张可能漏过。
    uncontrolled_actions_expanded = bool(non_phase58_actions_expanded or (bool(phase58_report.get("actions_expanded")) and not controlled_actions_expansion) or PHASE64_ACTIONS_EXPANDED)  # 新增代码+Phase64ParityPlusMatrix: 判断是否存在无保护动作面扩张；如果没有这行代码，总矩阵无法区分受控能力和危险扩张。
    passed = bool(all_phase_contracts_passed and non_fake_acceptance and visible_terminal_gate and approval_bypass_blocked and controlled_actions_expansion and not uncontrolled_actions_expanded)  # 新增代码+Phase64ParityPlusMatrix: 汇总最终通过条件；如果没有这行代码，main 无法用退出码表达成功或失败。
    return {"marker": PHASE64_WINDOWS_PARITY_PLUS_MATRIX_MARKER, "ok_token": PHASE64_WINDOWS_PARITY_PLUS_MATRIX_OK_TOKEN, "model": PHASE64_PARITY_PLUS_MATRIX_MODEL, "phase_count": phase_count, "expected_phase_count": PHASE64_EXPECTED_PHASE_COUNT, "all_phase_contracts_passed": all_phase_contracts_passed, "non_fake_acceptance": non_fake_acceptance, "visible_terminal_gate": visible_terminal_gate, "approval_bypass_blocked": approval_bypass_blocked, "controlled_actions_expansion": controlled_actions_expansion, "uncontrolled_actions_expanded": uncontrolled_actions_expanded, "actions_expanded": PHASE64_ACTIONS_EXPANDED, "passed": passed, "phase_flags": phase_flags, "phase_results": phase_results, "phase_cli_lines": phase_cli_lines, "phase_reports": phase_reports, "state_dir": str(root), "scenario_path": str(DEFAULT_PHASE64_SCENARIO_PATH)}  # 新增代码+Phase64ParityPlusMatrix: 返回完整最终矩阵报告；如果没有这行代码，CLI、测试和真实终端拿不到结构化结果。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，run_phase64_parity_plus_matrix_contract 到此结束；如果没有这个边界说明，初学者不容易看出总验收运行范围。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，phase64_cli_line 把最终矩阵报告转成稳定 token 行；如果没有这段函数，真实终端场景需要解析复杂 JSON，作者意图是让最终回答可复制可验收。
def phase64_cli_line(report: dict[str, Any]) -> str:  # 新增代码+Phase64ParityPlusMatrix: 定义 Phase64 CLI 行格式化函数；如果没有这行代码，main 无法打印固定顺序 token。
    return f"{PHASE64_WINDOWS_PARITY_PLUS_MATRIX_MARKER} {PHASE64_WINDOWS_PARITY_PLUS_MATRIX_OK_TOKEN} phase_count={int(report.get('phase_count', 0) or 0)} phase53_parity_gap={_bool_token(report.get('phase_flags', {}).get('phase53_parity_gap'))} phase54_native_reality_gate={_bool_token(report.get('phase_flags', {}).get('phase54_native_reality_gate'))} phase55_native_helper_v2={_bool_token(report.get('phase_flags', {}).get('phase55_native_helper_v2'))} phase56_real_screenshot_pipeline={_bool_token(report.get('phase_flags', {}).get('phase56_real_screenshot_pipeline'))} phase57_real_uia_locator={_bool_token(report.get('phase_flags', {}).get('phase57_real_uia_locator'))} phase58_real_sendinput_guard={_bool_token(report.get('phase_flags', {}).get('phase58_real_sendinput_guard'))} phase59_session_context={_bool_token(report.get('phase_flags', {}).get('phase59_session_context'))} phase60_persistent_grants={_bool_token(report.get('phase_flags', {}).get('phase60_persistent_grants'))} phase61_abort_streaming_hooks={_bool_token(report.get('phase_flags', {}).get('phase61_abort_streaming_hooks'))} phase62_high_level_tools={_bool_token(report.get('phase_flags', {}).get('phase62_high_level_tools'))} phase63_controller_takeover={_bool_token(report.get('phase_flags', {}).get('phase63_controller_takeover'))} all_phase_contracts_passed={_bool_token(report.get('all_phase_contracts_passed'))} non_fake_acceptance={_bool_token(report.get('non_fake_acceptance'))} visible_terminal_gate={_bool_token(report.get('visible_terminal_gate'))} approval_bypass_blocked={_bool_token(report.get('approval_bypass_blocked'))} controlled_actions_expansion={_bool_token(report.get('controlled_actions_expansion'))} uncontrolled_actions_expanded={_bool_token(report.get('uncontrolled_actions_expanded'))}"  # 新增代码+Phase64ParityPlusMatrix: 返回固定顺序 token 行；如果没有这行代码，验收器无法稳定匹配最终矩阵。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，phase64_cli_line 到此结束；如果没有这个边界说明，初学者不容易看出 CLI 文本范围。


# 新增代码+Phase64ParityPlusMatrix: 函数段开始，main 提供命令行自检入口；如果没有这段函数，真实终端无法直接运行 Phase64 总矩阵，作者意图是自动化和可见终端共用同一合同。
def main() -> int:  # 新增代码+Phase64ParityPlusMatrix: 定义命令行入口；如果没有这行代码，python -c 只能手写调用细节。
    report = run_phase64_parity_plus_matrix_contract()  # 新增代码+Phase64ParityPlusMatrix: 运行 Phase64 总矩阵合同；如果没有这行代码，CLI 输出没有真实依据。
    print(phase64_cli_line(report))  # 新增代码+Phase64ParityPlusMatrix: 打印稳定单行 token；如果没有这行代码，验收器无法快速匹配总结果。
    print(json.dumps(report, ensure_ascii=False, sort_keys=True))  # 新增代码+Phase64ParityPlusMatrix: 打印结构化报告便于人工复盘；如果没有这行代码，失败时不容易定位哪一阶段失败。
    print(PHASE64_WINDOWS_PARITY_PLUS_MATRIX_MARKER)  # 新增代码+Phase64ParityPlusMatrix: 单独打印 ready marker；如果没有这行代码，真实终端验收可能看不到明确阶段标记。
    return 0 if bool(report.get("passed")) else 1  # 新增代码+Phase64ParityPlusMatrix: 根据总合同结果返回退出码；如果没有这行代码，失败也可能被终端当成成功。
# 新增代码+Phase64ParityPlusMatrix: 函数段结束，main 到此结束；如果没有这个边界说明，初学者不容易看出命令行入口范围。


__all__ = ["DEFAULT_PHASE64_PARITY_PLUS_MATRIX_ROOT", "DEFAULT_PHASE64_SCENARIO_PATH", "PHASE64_EXPECTED_PHASE_COUNT", "PHASE64_EXPECTED_PHASE_IDS", "PHASE64_PARITY_PLUS_MATRIX_MODEL", "PHASE64_WINDOWS_PARITY_PLUS_MATRIX_MARKER", "PHASE64_WINDOWS_PARITY_PLUS_MATRIX_OK_TOKEN", "main", "phase64_cli_line", "run_phase64_parity_plus_matrix_contract"]  # 新增代码+Phase64ParityPlusMatrix: 限定公开导出名称；如果没有这行代码，from module import * 会暴露内部 helper。


if __name__ == "__main__":  # 新增代码+Phase64ParityPlusMatrix: 允许直接运行本模块；如果没有这行代码，初学者无法用 python 文件方式手动执行 Phase64 自检。
    raise SystemExit(main())  # 新增代码+Phase64ParityPlusMatrix: 调用 main 并传递退出码；如果没有这行代码，直接运行文件不会执行验收。
